name: Ghost Theme Pipeline
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Get theme code
        uses: actions/checkout@master
      - name: Setup testing environment
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run test with gscan
        run: |
          npm install --global gscan@latest
          gscan --v2 --error --verbose $GITHUB_WORKSPACE
      - name: Ending
        run: echo "All done."
  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.2.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: pitscherswelt-theme
      - name: Send Push Notification
        uses: techulus/push-github-action@v0.0.2
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MESSAGE: 'CI/CD --> completed successfully!'